### ISSUE TITLE
Final Report

### ISSUE THREAD

**Issue by AhmadAbouAdla1** [traffic-control-fyp-aub/ns3-gym#40]
Linked to #29 

Checklist:

- [x] Executive Summary

- [x] Intro (Motivation + Desired Needs)

- [x] Requirements and Deliverables

- [x] Technical and Non-Technical Constraints

- [x] Literature Review

- [x] Applicable Standards

- [x] Solution Methodology

- [ ] Design (Alternatives + Iterations + Final Decision)

- [ ] Implementation

- [ ] Experiment Design and Training

- [ ] Broad Impact

- [ ] New Engineering Concepts Learned

- [x] References

- [ ] Appendix

**Comment by AhmadAbouAdla1** [comment]
I will begin by adding what can be added from the old report, and ticking the corresponding sections from the checklist. Moreover, I will ask you (@alt113 @jKh98 ) for any info that I cannot write by myself.

**Comment by AhmadAbouAdla1** [comment]
@alt113 @jKh98 

I added everything that is relevant and checked the corresponding parts. It is almost done. I have the following remarks:

1. I added the part that was in preliminary implementation in the progress report to the implementation section in the newer one. We must add all new info that should be added to this section

2. For **Design Decision**, **Design Iterations**, and **Experiment and Testing**, I have an image of the broad idea (ie trying each scenario with each algorithm) but it got messy and unorganized real quick. I f you could help me with these sections, it would be great.

3. I wrote the broader impact section, but I have some doubts concerning the global impact as I "shaffatet" most of the way.

4. ~~As for the headings and typos, I fixed and organized everything.~~

5. ~~Since they told us to precisely follow this template, there is no list of equations/figures, unlike the progress report. Thus, do we add it or not?~~

6. ~~So now when we finalize the report I can easily finish the slides in which I get a clear image of what's important to include (ie not all figures)~~

**Comment by alt113** [comment]
@AhmadAbouAdla1 I updated your comment to be more relevant for the issue and changed the bullets to numbers that way it is easier to reference each point and add my feedback to it. 

In terms of [1] I feel it would be better if you tag the person you need help from in the original comment at the top of the issue thread because any other comment honestly will get lost and not payed attention to (or at least for me anyways). 

For [2], same comment as [1] maybe even go further and assign comment notes to us within the Google Doc. 

For [3], I didn't quite get what you mean by "shaffatet"?

**Comment by AhmadAbouAdla1** [comment]
Alright, I will isolate all my comments in the Google Doc. As for [3], I didn't find a specific global impact, so I just wrote about the generality and scalability of NGS.
